language: go

go:
  - 1.8
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
after_success:
  - gox -osarch="linux/amd64" -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
deploy:
  provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  file: "dist/linux_amd64_consul-launcher"
  skip_cleanup: true
  on:
    tags: true
